GET https://oop-course.herokuapp.com/api/v1/user

###
POST https://oop-course.herokuapp.com/api/v1/user
Content-Type: application/json

{
  "email": "oleksii.mytnyk@ucu.edu.ua",
  "dob": "2004-01-30"
}